name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Format code
        run: |
          gofmt -w .
          git diff --exit-code || (echo "Code was not formatted, please commit formatted files." && exit 1)


      - name: Run tests
        run: go test ./...
